### PR TITLE
Updated challenge container to run as non-root

### PR DESCRIPTION
**Pull request by rustla**
Updated existing example challenge container to run as non-root user

### CODE REVIEW

**Comment by sudosammy** [comment]
@C-Sto happy with this? Looks fine to me.

**Comment by sudosammy** [comment]
We could ask @rustla to update the other sample game files to also not run as root 🤔

**Comment by C-Sto** [comment]
Looks fine - I'll have a play with it tonight and update the other files accordingly (unless @rustla gets to it first). I suspect there will be _some_ instances where we can't avoid running as root, but we can deal with that on a case-by-case basis.

**Comment by sudosammy** [comment]
This is an important change to be made, @rustla could you please update the other sample challenges in this repo to also run as low-privileged users and then I will merge this.

**Comment by sudosammy** [comment]
Alright, so Kubernetes doesn't support `sysctls` when converting docker-compose files, so that's a bit of a problem. The preferred solution would be to bind to >1024 in the containers - could be tough with Apache images. I will ponder this and merge at the next meeting.

**Pull request merged**
